site_name: myevan.net
theme: material
markdown_extensions:
    - codehilite
    - toc:
        permalink: True
nav:
    - "home": index.md
    - "os":
        - "mac":
            - "pkg": mac_package_mgr_homebrew.md
            - "zsh": 
                - "setup": mac_zsh_setup.md
                - "pyenv": mac_zsh_pyenv.md
            - "vm":
                - "static ip": vmware_fusion_8_static_ip.md
                - "port forwarding": vmware_fusion_8_port_forwarding.md
            - "ide": mac_xcode_command_line.md
            - "python":
                - "pyenv": mac_python_pyenv.md
                - "pyvenv": mac_python_virtualenvwrapper.md
            - "hangul": mac_hangul_key_capslock.md
            - "vim": mac_vim.md
            - "vs code": mac_vs_code.md
            - "root": mac_root_enable.md
            - "hostname": mac_terminal_hostname.md
        - "ubuntu": 
            - "python": ubuntu_python_pyenv.md
            - "docker": ubuntu_docker.md
            - "nodejs": ubuntu_node.js.md
            - "sudo": ubuntu_sudo.md
            - "ip": ubuntu_setup_ip.md
            - "time": ubuntu_local_time_zone.md
        - "windows": 
            - "vm":
                - "ubuntu":
                    - "installation": hyper_v_ubuntu_installation.md
                    - "disk expanding": hyper_v_ubuntu_disk_expanding.md
                - "freenas": hyper_v_freenas_setup.md
            - "ide": vs2015_download.md
            - "python": windows_python_virtualenv.md
            - "editor": windows_vscode_python_virtualenv.md
            - "remote": windows_remote_desktop_port.md
            - "hangul": windows_hangul_key_capslock.md
            - "user": 
                - "management": windows_user_management.md
                - "remote desktop": windows_remote_desktop_user_deny.md
            - "sync": windows_sync_robocopy.md
            - "pkg": windows_package_mgr_choco.md            
    - "doc":
        - "mkdocs": 
            - "windows": windows_python_mkdocs.md
            - "mkdocs toc": mkdocs_toc_hide.md
        - "github.io":
            - "mkdocs": github_io_mkdocs.md
            - "custom domain": github_io_custom_domain.md
    - "vcs":
        - "git":
            - "bash prompt": git_bash_prompt.md
            - "hosting": git_windows_hosting.md
            - "gitlab": 
                - "installation": gitlab_ubuntu_installation.md
            - "gitswarm": 
                - "require": helix_gitswarm_requirements.md
                - "install": helix_gitswarm_ubuntu_installation.md
                - "admin": helix_gitswarm_ubuntu_administration.md
                - "issue": helix_gitswarm_ubuntu_mirror_repository_delete.md
        - "helix":
            - "linux":
                - "daemon": helix_linux_perforce_daemon.md
                - "backup": helix_linux_perforce_backup.md
                - "restore": helix_linux_perforce_restore.md
            - "windows":
                - "svn migration": helix_windows_perforce_svn_migration.md
                - "perforce daemon": helix_windows_perforce_daemon.md
                - "perforce service": helix_windows_perforce_service.md
    - "term":
        - "vim config": vim_config.md
        - "git config": git_config.md
        - "screen": screen.md
        - "jupyter": jupyter.md
    - "editor":
        - "vscode":
            - "vim": vscode_ext_vim.md
            - "remote-ssh": vscode_ext_remote_ssh.md
            - "dev":
                - "tutorial": vscode_ext_get_started.md
                - "hello": vscode_ext_hello_world.md
    - "engine":
        - "tcod": python_tcod.md
        - "node.js": mac_node_js_get_started.md
        - "emscripten": emscripten_get_started.md
        - "ue4": 
            - "windows":
                - "setup":
                    - "engine": ue4_windows_setup_engine.md
                    - "project": ue4_windows_setup_project.md
                    - "visual studio": ue4_windows_setup_visual_studio.md
                - "build": ue4_windows_build.md
                - "debug":
                    - "uat": ue4_windows_debug_uat.md
            - "setup": ue4_setup_script.md
            - "build":
                - "build tool": ue4_build_tool.md
                - "compile": ue4_boost_compile_times.md
                - "processor": ue4_processor_count_multiplier.md
                - "unity": ue4_faster_without_unity.md
                - "pch": ue4_min_files_using_precompiled_header.md
                - "dbg help": ue4_build_crash_debug_helper.md
            - "plugin":
                - "not_found": ue4_plugin_module_not_found.md
                - "skip": ue4_plugin_skip.md
            - "network": ue4_dedicated_server.md
            - "gitignore": ue4_windows_vs_git_ext_gitignore.md
    - "rosetta":
        - "UnrealEnginePython": rosetta/UnrealEnginePython/README.md
        - "pyjs": rosetta/pyjs/about.md

